apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xeventdrivenservices.platform.bizmatters.io
spec:
  group: platform.bizmatters.io
  names:
    kind: XEventDrivenService
    plural: xeventdrivenservices
  claimNames:
    kind: EventDrivenService
    plural: eventdrivenservices
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              description: "EventDrivenService specification for deploying NATS JetStream consumer services with KEDA autoscaling"
              required:
                - image
                - nats
              properties:
                image:
                  type: string
                  description: "Container image reference (registry/repository:tag or registry/repository@sha256:digest)"
                  pattern: '^[a-z0-9]+((\.|_|__|-+)[a-z0-9]+)*(\/[a-z0-9]+((\.|_|__|-+)[a-z0-9]+)*)*(:[a-zA-Z0-9_][a-zA-Z0-9._-]{0,127}|@sha256:[a-f0-9]{64})?$'
                  example: "ghcr.io/org/my-service:v1.0.0"

                size:
                  type: string
                  description: "Resource size allocation (small: 250m-1000m CPU, 512Mi-2Gi memory; medium: 500m-2000m CPU, 1Gi-4Gi memory; large: 1000m-4000m CPU, 2Gi-8Gi memory)"
                  enum:
                    - small
                    - medium
                    - large
                  default: medium

                nats:
                  type: object
                  description: "NATS JetStream configuration"
                  required:
                    - stream
                    - consumer
                  properties:
                    url:
                      type: string
                      description: "NATS server URL for client connections"
                      default: "nats://nats.nats.svc:4222"
                      pattern: '^nats://[a-z0-9.-]+:[0-9]+$'

                    stream:
                      type: string
                      description: "JetStream stream name (must exist before deployment)"
                      minLength: 1
                      maxLength: 255
                      pattern: '^[A-Z0-9_]+$'
                      example: "AGENT_EXECUTION"

                    consumer:
                      type: string
                      description: "Consumer group name for this service"
                      minLength: 1
                      maxLength: 255
                      pattern: '^[a-z0-9-]+$'
                      example: "agent-executor-workers"

                secretRefs:
                  type: array
                  description: "Array of secret references for environment variable injection (supports Crossplane-generated and ESO-synced secrets)"
                  items:
                    type: object
                    required:
                      - name
                    properties:
                      name:
                        type: string
                        description: "Name of the Kubernetes Secret to reference"
                        minLength: 1
                        maxLength: 253
                        pattern: '^[a-z0-9]([-a-z0-9]*[a-z0-9])?$'

                      env:
                        type: array
                        description: "Array of individual secret key mappings to environment variables (for Crossplane secrets with specific key structure)"
                        items:
                          type: object
                          required:
                            - secretKey
                            - envName
                          properties:
                            secretKey:
                              type: string
                              description: "Key name in the secret"
                              minLength: 1
                              example: "endpoint"

                            envName:
                              type: string
                              description: "Environment variable name in the container"
                              minLength: 1
                              pattern: '^[A-Z_][A-Z0-9_]*$'
                              example: "POSTGRES_HOST"

                      envFrom:
                        type: boolean
                        description: "If true, mount all secret keys as environment variables using envFrom (for ESO secrets)"
                        default: false

                imagePullSecrets:
                  type: array
                  description: "Array of image pull secret names for private container registries"
                  items:
                    type: object
                    required:
                      - name
                    properties:
                      name:
                        type: string
                        description: "Name of the image pull secret"
                        minLength: 1
                        maxLength: 253
                        pattern: '^[a-z0-9]([-a-z0-9]*[a-z0-9])?$'
                        example: "ghcr-pull-secret"

                initContainer:
                  type: object
                  description: "Optional init container configuration for database migrations or pre-start tasks (uses same image as main container)"
                  required:
                    - command
                  properties:
                    command:
                      type: array
                      description: "Command to execute in the init container"
                      minItems: 1
                      items:
                        type: string
                      example: ["/bin/bash", "-c"]

                    args:
                      type: array
                      description: "Arguments to pass to the command"
                      items:
                        type: string
                      example: ["cd /app && ./scripts/ci/run-migrations.sh"]
